# Generated by Django 4.1.1 on 2022-10-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_band_active_band_biography_band_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='official_home_page',
            field=models.URLField(blank=True, null=True),
        ),
    ]
