# Generated by Django 4.1.1 on 2022-10-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_listing_band'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='status',
            field=models.CharField(choices=[('New', 'Nouveau'), ('old', 'Ancien')], default='', max_length=5),
            preserve_default=False,
        ),
    ]
