# Generated by Django 4.1.1 on 2022-10-11 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_rename_status_band_stat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='band',
            old_name='stat',
            new_name='statuts',
        ),
    ]
